### ISSUE TITLE
ServiceFault Exception if a user has no security roles assigned

### ISSUE THREAD

**Issue by Prospero100** [MscrmTools/MsCrmTools.UserSettingsUtility#17]
When updating a list of users if there are any in the list that do not have a security role assigned, then a fatal exception is thrown causing the XrmToolBox to close. The exception message is:

_System.ServiceModel.FaultException'1[Microsoft.Xrm.Sdk.Organization.ServiceFault]: SecLib::RetrievePriviledgeForUser failed - no roles are assigned to the user. Returned HR = -2147209463, User : [usersGuid] (Fault Detail is equal to Microsoft.Xrm.Sdk.OrganizationServiceFault)_

I'll see if I can clone the code locally and fix up :)
Regards,
Paul

**Comment by bwmodular** [comment]
I'll take a look at this one. You also get a similar failure if the user is disabled. My thinking is that we just let these fail silently, rather than having to report on them. But we could also have a dialogue which says 'User could not be updated as they have no security roles - Do you wish to Cancel or Continue or Continue and Skip over similar errors'.  
Any preference?

**Comment by MscrmTools** [comment]
Or maybe a log window that will report users that failed to update

**Comment by bwmodular** [comment]
Yes, OK, I'll do the latter. It's the least intrusive and most informative.....

**Comment by bwmodular** [comment]
Not much room on that screen to add a log window though - should I make it pop out (if that's possible)?

**Comment by MscrmTools** [comment]
We could add a panel at the bottom of the plugin

**Comment by bwmodular** [comment]
I've worked out how do quite a nice logging panel, but I'm really struggling with screen layout. I think it needs to be full screen in order to display any useful information, but if I put it below all the Right Hand tick boxes it's going to be so low down that most users won't even realise its there! Any ideas before I wreck the layout?

**Comment by MscrmTools** [comment]
Can you show a screenshot of what you have so far?
